### ISSUE TITLE
Dependencies missing

### ISSUE THREAD

**Issue by korinrider** [TechnoWolfTV/Adventurelands#1]
Some mods have unsatisfied dependencies:
 - 3d_armor is missing: player_api default
 - 3d_armor_ip is missing: 3d_armor
 - 3d_armor_sfinv is missing: 3d_armor
 - 3d_armor_stand is missing: 3d_armor
 - 3d_armor_ui is missing: 3d_armor
 - armor_admin is missing: 3d_armor
 - armor_bronze is missing: 3d_armor
 - armor_cactus is missing: 3d_armor
 - armor_diamond is missing: 3d_armor
 - armor_gold is missing: 3d_armor
 - armor_mithril is missing: 3d_armor
 - armor_steel is missing: 3d_armor
 - armor_wood is missing: 3d_armor
 - shields is missing: 3d_armor default
 - wieldview is missing: 3d_armor
 - computers is missing: basic_materials xcompat
 - home_vending_machines is missing: xcompat
 - ambience is missing: default
 - anvil is missing: default
 - backrooms_nodes is missing: doors default
 - basic_materials is missing: xcompat
 - bees is missing: vessels default
 - blazing_tools is missing: default
 - bows_epic is missing: tnt default
 - builtin_item is missing: default
 - castle_farming is missing: bucket wool default
 - castle_gates is missing: default
 - castle_lighting is missing: default
 - castle_shields is missing: dye default
 - castle_storage is missing: default
 - castle_tapestries is missing: wool unifieddyes default
 - caverealms is missing: default
 - cblocks is missing: default
 - charcoal is missing: default
 - digtron is missing: default
 - edit_skin is missing: player_api
 - facade is missing: default
 - flowerbeds is missing: default flowers
 - hangglider is missing: dye wool default
 - hbarmor is missing: 3d_armor hudbars

Install and enable the required mods, or disable the mods causing errors.
Note: this may be caused by a dependency cycle, in which case try updating the mods.

**Comment by TechnoWolfTV** [comment]
I've attempted to reproduce the dependency issues you've reported and cannot. There are currently no unsatisfied dependencies when the game is properly installed and is otherwise unmodified. Have you properly installed Adventurelands as a game? **I have just added installation instructions to the README file for clarification.**
